title: Meri-Imperiumin venekeittokirja
name: Keittokirja
author: meri-imperiumi
language: fi
defaults:
    - scope:
          path: ""
          type: recipes
      values:
          layout: recipe
collections:
    recipes:
        output: true
        permalink: /:name/
        sort_by: category
exclude:
    - .github
    - .gitignore
    - Gemfile
    - Gemfile.lock
    - README.md
    - "*.base"
    - .obsidian
    - _templates
    - package.json
    - package-lock.json
    - node_modules
